#!/bin/bash
notify-send "script with hooks started"

#setxkbmap -layout "us,ru"
#setxkbmap -option "grp:caps_toggle,grp_led:scroll,compose:ralt"
#notify-send "keyboard layout changed"

dropbox start
notify-send "dropbox started"

notify-send "script with hooks finished"
